apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      livenessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 30
        timeoutSeconds: 1
      volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data
      volumes:
      - name: redis-persistent-storage
        gcePersistentDisk:
          pdName: redis-disk
          fsType: ext4
