version: '2'
services:
  wordpress:
    image: wordpress
    restart: always
    links:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
